'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePrefs} from '@/components/Prefs';
import {projectRequest,projectName,projectError} from '@/lib/owner-projects';

export default function OwnerProjectControl({project,onUpdated}) {
  const {locale}=usePrefs();const text=(zh,en)=>locale.startsWith('zh')?zh:en;
  const [mode,setMode]=useState('new'),[name,setName]=useState(''),[spaceId,setSpace]=useState(''),[roomId,setRoom]=useState('');
  const [spaces,setSpaces]=useState([]),[cursor,setCursor]=useState(null),[candidateError,setCandidateError]=useState(null),[loadingSpaces,setLoadingSpaces]=useState(false),[loaded,setLoaded]=useState(false);
  const [creation,setCreation]=useState(null),[recovery,setRecovery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(null),[storageKey,setStorageKey]=useState(null);
  const mutation=useRef(false),command=useRef(null),mounted=useRef(false),generation=useRef(0);
  useEffect(()=>{mounted.current=true;generation.current+=1;return()=>{mounted.current=false;generation.current+=1;};},[project?.id]);const blocked=creation&&creation.phase!=='complete';
  useEffect(()=>{let alive=true;fetch('/console/server-login',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(10000)}).then(async response=>{if(!response.ok)throw new Error('sign_in_required');return response.json();}).then(async info=>{if(!alive)return;if(!info.activeProfileId)throw new Error('sign_in_required');const key=`hagency.matrix.creation.${info.activeProfileId}.${project?.id||'project'}`;setStorageKey(key);const stored=sessionStorage.getItem(key);let saved;try{saved=JSON.parse(stored);}catch{saved={id:stored};}const id=saved?.id;if(id){if(saved.input)command.current={id,input:saved.input,key:JSON.stringify(saved.input)};setCreation({commandId:id,phase:'unknown'});try{const value=await projectRequest(`matrix-creations/${encodeURIComponent(id)}`);if(alive){setCreation(value.creation);if(value.creation.phase==='complete')sessionStorage.removeItem(key);}}catch(e){if(alive){setError(e.message);if(e.status===404)setCreation({commandId:id,phase:'unrecorded'});}}}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[project?.id]);
  async function loadSpaces(next=null) {
    if(loadingSpaces)return;setLoadingSpaces(true);setCandidateError(null);
    try {const value=await projectRequest(`owner-projects/space-candidates${next?`?cursor=${encodeURIComponent(next)}`:''}`);setSpaces(previous=>next?[...new Map([...previous,...value.spaces].map(s=>[s.spaceId,s])).values()]:value.spaces);setCursor(value.nextCursor);setLoaded(true);if(value.incomplete)setCandidateError(text('部分 Space 暂时无法读取，请刷新重试。','Some Spaces could not be read. Refresh to retry.'));}
    catch(e){setLoaded(true);setCandidateError(projectError(e.message,text));}finally{setLoadingSpaces(false);}
  }
  useEffect(()=>{if(mode==='existing'&&!project&&!loaded&&!loadingSpaces)loadSpaces();},[mode,project,loaded,loadingSpaces]);
  async function run(action) {if(mutation.current||!mounted.current)return;const started=generation.current;const active=()=>mounted.current&&started===generation.current;mutation.current=true;setBusy(true);setError(null);try{await action(active);}catch(e){if(active())setError(e.message);}finally{mutation.current=false;if(active())setBusy(false);}}
  function completed(next) {setCreation(next);if(next.phase==='complete'){sessionStorage.removeItem(storageKey);command.current=null;if(project){setName('');onUpdated?.();}else window.location.assign(next.project?.id?`/console/projects/?project=${encodeURIComponent(next.project.id)}`:'/console/projects/');}}
  async function submit(event) {
    event.preventDefault();if(busy||blocked||!storageKey)return;
    await run(async active=>{
      if(mode==='existing') {const result=await projectRequest(project?`owner-projects/${encodeURIComponent(project.id)}/rooms`:'owner-projects','POST',project?{roomId:roomId.trim()}:{spaceId:spaceId.trim()});if(!active())return;if(project){setRoom('');onUpdated?.();}else window.location.assign(result.project?.id?`/console/projects/?project=${encodeURIComponent(result.project.id)}`:'/console/projects/');return;}
      const input={kind:project?'room':'space',name:name.trim(),...(project?{projectId:project.id,spaceId:project.spaceId}:{})};const key=JSON.stringify(input);if(!command.current||command.current.key!==key)command.current={key,id:crypto.randomUUID(),input};sessionStorage.setItem(storageKey,JSON.stringify({id:command.current.id,input}));setCreation({commandId:command.current.id,phase:'unknown'});const result=await projectRequest('matrix-creations','POST',{...input,commandId:command.current.id});if(active())completed(result.creation);
    });
  }
  return <section className={project?'panel owner-create-form':'owner-workspace owner-create-page'} data-owner-projects>
    {!project&&<Link className="owner-back" href="/projects/">← {text('所有 Projects','All projects')}</Link>}
    <header className="owner-page-heading"><div><h1>{project?text('添加讨论组','Add a room'):text('创建 Project','Create project')}</h1><p className="dim">{project?text(`添加到 ${projectName(project,text)}。讨论组的成员独立管理。`,`Add a room to ${projectName(project,text)}. Room membership is independent.`):text('Project 是 Hagency 中组织讨论组与 Agents 的工作单元，关联一个 Matrix Space。','A project organizes rooms and agents in Hagency and connects to one Matrix Space.')}</p></div></header>
    <form className="owner-create-form" onSubmit={submit} data-project-create>
      <fieldset className="owner-choice-group" disabled={busy||blocked}><legend>{project?text('讨论组来源','Room source'):text('关联的 Space','Connected Space')}</legend>
        <label className={mode==='new'?'owner-choice selected':'owner-choice'}><input type="radio" name="project-source" value="new" checked={mode==='new'} onChange={()=>setMode('new')}/><span><strong>{project?text('新建讨论组','Create a new room'):text('新建 Space','Create a new Space')}</strong><small>{project?text('在此 Project 下创建私有讨论组。','Create a private room under this project.'):text('默认方式。创建 Project 时同时创建 Space。','Default. Create a Space together with this project.')}</small></span></label>
        <label className={mode==='existing'?'owner-choice selected':'owner-choice'}><input type="radio" name="project-source" value="existing" checked={mode==='existing'} onChange={()=>setMode('existing')}/><span><strong>{project?text('使用已有讨论组','Use an existing room'):text('绑定已有 Space','Connect an existing Space')}</strong><small>{project?text('登记已属于此 Space 的讨论组。','Register a room already linked to this Space.'):text('选择当前账号已加入、且有管理权限的 Space。','Choose a Space you joined and have permission to manage.')}</small></span></label>
      </fieldset>
      {mode==='new'?<label>{project?text('讨论组名称','Room name'):text('Project 名称','Project name')}<input autoFocus required maxLength={128} disabled={busy||blocked} value={name} onChange={e=>setName(e.target.value)} placeholder={project?text('例如：产品讨论','e.g. Product discussion'):text('例如：产品研发','e.g. Product development')}/></label>:project?<label>{text('讨论组 ID','Room ID')}<input required disabled={busy||blocked} value={roomId} onChange={e=>setRoom(e.target.value)} placeholder="!room:example.org"/></label>:<div className="owner-space-picker">
        <label>{text('选择 Space','Choose a Space')}<select required disabled={busy||blocked||loadingSpaces} value={spaceId} onChange={e=>setSpace(e.target.value)}><option value="">{loadingSpaces?text('正在加载…','Loading…'):text('选择已加入的 Space','Choose a joined Space')}</option>{spaces.map(space=><option key={space.spaceId} value={space.spaceId} disabled={Boolean(space.projectId)}>{space.name||space.spaceId}{space.projectId?text('（已绑定 Project）',' (already connected)'):''}</option>)}</select></label>
        {loaded&&!spaces.length&&!candidateError&&<p className="dim">{text('本页尚未找到已加入的 Space。你也可以新建 Space。','No joined Spaces found on this page. You can create a new Space.')}</p>}
        {candidateError&&<p role="alert">{candidateError}</p>}
        <div className="btn-row"><button className="btn" type="button" disabled={loadingSpaces||busy||blocked} onClick={()=>loadSpaces()}>{text('刷新 Space 列表','Refresh Spaces')}</button>{cursor&&<button className="btn" type="button" disabled={loadingSpaces||busy||blocked} onClick={()=>loadSpaces(cursor)}>{text('加载更多','Load more')}</button>}</div>
      </div>}
      <p className="owner-form-hint">{mode==='new'?text('使用你的 Matrix 账号创建，并邀请 Hagency 服务账号以启用 Agents。','Created with your Matrix account. The Hagency service account is invited to enable agents.'):project?text('已有讨论组需与此 Space 关联；绑定不会改变成员或房间设置。','The room must already belong to this Space. Connecting it does not change members or room settings.'):text('保留 Space 的名称、成员和房间设置。Project 使用 Space 的名称；服务器会核验你的管理权限。','Keep the Space’s name, members and settings. The project uses its name; the server verifies your management permission.')}</p>
      {error&&<p className="owner-notice" role="alert">{projectError(error,text)}</p>}
      <div className="btn-row"><button className="btn owner-primary" disabled={busy||blocked||!storageKey}>{busy?text('正在处理…','Working…'):project?text('添加讨论组','Add room'):text('创建 Project','Create project')}</button>{!project&&<Link className="btn" href="/projects/">{text('取消','Cancel')}</Link>}</div>
    </form>
    {blocked&&creation.phase!=='unrecorded'&&<section className="owner-notice" data-matrix-creation-result><h3>{text('需要确认上次创建结果','Confirm the previous creation')}</h3><p>{text('上次创建尚未确认完成。请恢复原操作，避免重复创建。','The previous creation is not confirmed. Resume it to avoid creating a duplicate.')}</p>{creation.lastError&&<p>{projectError(creation.lastError,text)}</p>}<details><summary>{text('我已找到创建的 Space 或讨论组','I found the created Space or room')}</summary><label>Matrix ID<input value={recovery} onChange={e=>setRecovery(e.target.value)} disabled={busy} placeholder="!room:example.org"/></label></details><button className="btn" type="button" disabled={busy} onClick={()=>run(async active=>{const result=await projectRequest(`matrix-creations/${encodeURIComponent(creation.commandId)}/resume`,'POST',recovery.trim()?{roomId:recovery.trim()}:{});if(active())completed(result.creation);})}>{text('恢复上次创建','Resume previous creation')}</button></section>}
    {creation?.phase==='unrecorded'&&<div className="owner-notice" data-unrecorded-creation><p>{text('暂时没有找到原请求记录。保留原请求重试，避免重复创建。','The original request is not recorded yet. Retry the same request to avoid a duplicate.')}</p>{command.current?.input&&<button className="btn" type="button" disabled={busy} onClick={()=>run(async active=>{const result=await projectRequest('matrix-creations','POST',{...command.current.input,commandId:creation.commandId});if(active())completed(result.creation);})}>{text('重试原请求','Retry original request')}</button>}</div>}

  </section>;
}
