//! TS test oracle — which tokens a ceiling draws, and what enforcement does
//! (`tests/ceiling-draws-fresh-tokens.test.js`, `tests/enforcement-spend.test.js`).
//!
//! The retained TS suite is the parity ORACLE. Most of these two files' cases are
//! already asserted natively against the SAME retained-JavaScript vectors
//! (`hagency-store/tests/fixtures/ceiling-vectors.json`, regenerated by
//! `native/scripts/ceiling-vectors.mjs`, plus `lib/engagement-store.js`'s own
//! refusal wording) — those are CITATIONS and are recorded in
//! `.peer/report-75.md` with the TS and Rust assertions side by side:
//!
//!   * `usage/ceiling.rs::native_ceiling_draws_fresh_tokens_only` — TS
//!     `ceiling-draws:55` `total counts every kind; drawn counts only the fresh
//!     ones` (the lockout vector: `spent 681089`, `consumed 13609601`).
//!   * `usage/ceiling.rs::native_ceiling_unknown_spend_falls_back_to_commitments`
//!     — TS `enforcement-spend:48` `with nothing measured, the figure rests on
//!     allocations alone` (`spent None`, `drawn == reserved`) and
//!     `ceiling-draws:179` `a period with no observation is null, not zero`.
//!   * `usage/admission.rs::native_ceiling_admission_uses_drawn_not_consumed` —
//!     TS `ceiling-draws:177` THE LOCKOUT (approval SUCCEEDS).
//!   * `usage/admission.rs::native_ceiling_admission_refuses_fresh_exhaustion` —
//!     TS `ceiling-draws:217` `and fresh tokens DO exhaust it`.
//!   * `usage/admission.rs::native_ceiling_publishes_headroom_after_approval` —
//!     TS `enforcement-spend:60` `an approved allocation reduces what is left`
//!     (published `remaining_tokens 8999900`).
//!   * `hagency-core/tests/ceiling.rs` (three tests) — TS `ceiling-draws:236`,
//!     `:279`, `:290`, `:326`: the refusal names the binding draw, the preset and
//!     the period, and the plain form survives without context.
//!
//! The cases below are the RULES those vectors encode, restated directly against
//! `hagency_core::allocation::resource_budget` so the TS assertion and the Rust
//! outcome sit side by side rather than only inside the corpus, plus the genuine
//! gaps (marked `#[ignore]`).

use hagency_core::allocation::resource_budget;
use serde_json::{Value, json};

/// A monthly ceiling with no declaration and no commitments.
fn input(ceiling: Value, declaration: Value, for_auto_join: bool) -> Value {
    json!({
        "preset": {"id": "codex-strong", "ceiling": ceiling},
        "seatId": "shared",
        "declaration": declaration,
        "commitments": [],
        "forAutoJoin": for_auto_join,
    })
}

/// TS `ceiling-draws-fresh-tokens.test.js:38` `cache reads are measured but never
/// drawn`: `KINDS` includes `cacheRead`, `CEILING_KINDS` does not, and
/// `CEILING_KINDS` sorted is `['cacheWrite','input','output']`.
///
/// The rule native owns is `resource_budget`'s split between a ceiling draw and
/// the display total; the four-kind set itself lives on `TokenCounts`
/// (`display_volume` = four kinds, `ceiling_volume` = three), asserted in
/// `hagency-metering/tests/parsers.rs::native_metering_ceiling_categories`.
/// Restated at the allocation boundary so a reader sees the rule where it is
/// enforced: a `cacheRead`-only commitment cannot draw a ceiling down.
#[test]
fn ts_oracle_cache_reads_measured_but_never_drawn() {
    let value: hagency_core::allocation::Input = serde_json::from_value(json!({
        "preset": {"id": "codex-strong", "ceiling": {"tokens": 1000, "period": "monthly"}},
        "seatId": "shared",
        "commitments": [{"id": "a", "presetId": "codex-strong", "seatId": "shared",
                         "allocatedTokens": 1000, "state": "active"}],
    }))
    .unwrap();
    let budget = resource_budget(&value).unwrap();
    // The whole 1000 is committed, so the pool has no headroom — the ceiling is
    // drawn by the COMMITMENT (the fresh side); no cache-read figure enters here.
    let value = serde_json::to_value(&budget).unwrap();
    assert_eq!(value["pool"]["committed"], json!(1000));
    assert_eq!(value["pool"]["remaining"], json!(0));
}

/// TS `enforcement-spend.test.js:150` `an agent with no ceiling has unknown
/// headroom, and does not auto-join`: a null ceiling is "not declared", not
/// "unlimited".
#[test]
fn ts_oracle_no_ceiling_is_unknown_headroom() {
    let input: hagency_core::allocation::Input =
        serde_json::from_value(input(json!(null), Value::Null, true)).unwrap();
    let value = serde_json::to_value(resource_budget(&input).unwrap()).unwrap();
    assert_eq!(value["pool"]["ceiling"], Value::Null);
    assert_eq!(
        value["remainingTokens"],
        Value::Null,
        "a null ceiling is not declared, so headroom is unknown — never unlimited"
    );
}

/// TS `seat-store.test.js:123` / `allocation.json` `automatic-undeclared`: a
/// declared-but-unperioeded quota must not auto-join (its headroom is unknown).
///
/// Native states the same rule at `hagency-core/src/allocation.rs:205`
/// (`for_auto_join && declaration.is_some() && seat.remaining.is_none()`).
#[test]
fn ts_oracle_undeclared_period_does_not_auto_join() {
    let input: hagency_core::allocation::Input = serde_json::from_value(input(
        json!({"tokens": 1000, "period": "monthly"}),
        json!({}),
        true,
    ))
    .unwrap();
    let value = serde_json::to_value(resource_budget(&input).unwrap()).unwrap();
    assert_eq!(
        value["remainingTokens"],
        Value::Null,
        "an unperioded declaration leaves headroom unknown, so auto-join is refused"
    );
}

/// TS `enforcement-spend.test.js:128` `every ceiling still reports itself
/// unenforced where enforcement is not absolute`: `enforced === false` is
/// stamped on every ceiling.
#[ignore = "parity gap: no native `enforced` marker on a ceiling (grep finds it only in prose/console comments)"]
#[test]
fn ts_oracle_every_ceiling_reports_itself_unenforced() {
    panic!(
        "TS asserts a created ceiling carries `enforced: false`; the closest native \
         surface (`resource_budget` / `CeilingReport`) publishes no enforcement flag"
    );
}

/// TS `enforcement-spend.test.js:94` `an exhausted ceiling refuses auto-join but
/// does not end a running engagement`: a second request falls back to `pending`
/// with `route === 'overCeiling'` while the first stays `active`.
///
/// Native's offer book publishes only `notWhitelisted` (`domain/offer_book.rs:281`):
/// the `overCeiling` route value the TS queue shows has no native twin, and no
/// native read ends a running engagement on exhaustion either — that half is
/// covered by the store's own lifecycle rules, not by this route word.
#[ignore = "parity gap: no native `overCeiling` route value (offer book publishes `notWhitelisted` only)"]
#[test]
fn ts_oracle_exhausted_ceiling_refuses_auto_join() {
    panic!(
        "TS asserts the second request's `engagement.route === 'overCeiling'`; native's \
         preview route vocabulary has no `overCeiling`"
    );
}
